
services:
  hasura:
    image: hasura/graphql-engine:v2.42.0
    container_name: frontdesk_hasura
    restart: always
    ports:
      - "8080:8080" # Map Hasura port
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:Ksvsvkm2007@host.docker.internal:5432/frontdesk
      HASURA_GRAPHQL_ADMIN_SECRET: Ksvsvkm2007
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_LOG_LEVEL: "info"
      HASURA_GRAPHQL_DISABLE_TELEMETRY: "true"
