services:
  postgres:
    image: postgres:16
    container_name: frontdesk_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ksvsvkm2007
      POSTGRES_DB: frontdesk
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  hasura:
    image: hasura/graphql-engine:v2.42.0
    container_name: frontdesk_hasura
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:Ksvsvkm2007@postgres:5432/frontdesk
      HASURA_GRAPHQL_ADMIN_SECRET: Ksvsvkm2007
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_LOG_LEVEL: "info"

volumes:
  postgres_data:
